### ISSUE TITLE
argparse code probably outdated

### ISSUE THREAD

**Issue by SteveClement** [D4-project/BGP-Ranking#16]
After installing all the required deps it fails on a namespace error.

```
(venv) misp@misp-test:~/code/BGP-Ranking$ bgpranking
Traceback (most recent call last):
  File "/home/misp/code/BGP-Ranking/venv/bin/bgpranking", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/misp/code/BGP-Ranking/client/bin/bgpranking", line 43, in <module>
    if args.which == 'simple':
AttributeError: 'Namespace' object has no attribute 'which'
```

**Comment by Rafiot** [comment]
It is probably because a required paramater is not enforced by the script. Try `bgpranking simple --asn 6661`?
